# Generated by Django 2.2.2 on 2019-06-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('telefono_movil', models.CharField(max_length=10)),
                ('telefono_fijo', models.CharField(max_length=10)),
                ('direccion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_inicio_contratacion', models.DateField()),
                ('fecha_fin_contratacion', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRol', models.IntegerField()),
                ('nombreRol', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
