# Generated by Django 2.2.2 on 2019-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_fin_contratacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_inicio_contratacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='root', max_length=70),
        ),
        migrations.AlterField(
            model_name='rol',
            name='idRol',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
